In [46]:
import numpy as np
np.random.seed(1)


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 1, 2, 1, 2

# Create random input and output data
x = np.round(np.random.randn(N, D_in),2)
print('x = ', x)
y = np.round(np.random.randn(N, D_out),2)
print('y = ', y)

# Randomly initialize weights
w1 = np.round(np.random.randn(D_in, H),2)
w2 = np.round(np.random.randn(H, D_out),2)
print('w1 = ',w1)
print('w2 = ',w2)

learning_rate = 1e-6
for t in range(1):
    # Forward pass: compute predicted y
    a1 = x.dot(w1)
    print('h = ',h)
    h_relu = np.maximum(a1, 0)
    print('h_relu = ',h_relu)
    a2 = h_relu.dot(w2)
    print('a2 = ',a2)
    y_pred = np.maximum(a2, 0)
    print('y_pred = ',y_pred)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    print('grad_y_pred = ', grad_y_pred)
    grad_a2 = grad_y_pred.copy()
    grad_a2[a2 < 0] = 0
    print('grad_a2 = ', grad_a2)
    grad_w2 = h_relu.T.dot(grad_a2)
    print('grad_w2 = ', grad_w2)
    grad_h_relu = grad_a2.dot(w2.T)
    print('grad_h_relu = ', grad_h_relu)
    grad_a1 = grad_h_relu.copy()
    
    grad_a1[a1 < 0] = 0
    print('grad_a1 = ', grad_a1)
    grad_w1 = x.T.dot(grad_a1)
    print('grad_w1 = ', grad_w1)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

    print('w1 = ',w1)
    print('w2 = ',w2)

x =  [[ 1.62 -0.61]]
y =  [[-0.53 -1.07]]
w1 =  [[ 0.87]
 [-2.3 ]]
w2 =  [[ 1.74 -0.76]]
h =  [[2.8124]]
h_relu =  [[2.8124]]
a2 =  [[ 4.893576 -2.137424]]
y_pred =  [[4.893576 0.      ]]
0 30.560076627775995
grad_y_pred =  [[10.847152  2.14    ]]
grad_a2 =  [[10.847152  0.      ]]
grad_w2 =  [[30.50653028  0.        ]]
grad_h_relu =  [[18.87404448]]
grad_a1 =  [[18.87404448]]
grad_w1 =  [[ 30.57595206]
 [-11.51316713]]
w1 =  [[ 0.86996942]
 [-2.29998849]]
w2 =  [[ 1.73996949 -0.76      ]]


In [44]:
import torch
from torch.nn import Sigmoid
sig = Sigmoid()

np.random.seed(1)
torch.manual_seed(1)

dtype = torch.float
device = torch.device("cpu")

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.tensor([[ 1.62, -0.61]])
y = torch.tensor([[-0.53, -1.07]])

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.tensor([[ 0.87],[-2.3 ]], requires_grad = True)
w2 = torch.tensor([[ 1.74, -0.76]], requires_grad=True)

learning_rate = 1e-6
for t in range(1):
    # Forward pass: compute predicted y using operations on Tensors; these
    # are exactly the same operations we used to compute the forward pass using
    # Tensors, but we do not need to keep references to intermediate values since
    # we are not implementing the backward pass by hand.
    y_pred = x.mm(w1).clamp(min=0).mm(w2).clamp(min=0)

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call w1.grad and w2.grad will be Tensors holding the gradient
    # of the loss with respect to w1 and w2 respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    # An alternative way is to operate on weight.data and weight.grad.data.
    # Recall that tensor.data gives a tensor that shares the storage with
    # tensor, but doesn't track history.
    # You can also use torch.optim.SGD to achieve this.
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad

        print(w2.grad)
        print(w1.grad)
        
        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()

tensor([[30.5065,  0.0000]])
tensor([[ 30.5760],
        [-11.5132]])


In [24]:
x

tensor([[1.0100]])